version: '3.8'
services:
  postgres:
    image: postgres:15.4
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mana
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
    driver: local
